# Generated by Django 4.2.23 on 2026-09-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=60, unique=True, verbose_name='Nombre de la Especialidad')),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Especialidad Médica',
                'verbose_name_plural': 'Especialidades Médicas',
                'db_table': 'ESPECIALIDADES',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_nacional', models.CharField(db_column='MATRICULA_NACIONAL', max_length=20, unique=True, verbose_name='Matrícula Nacional')),
                ('matricula_provincial', models.CharField(blank=True, db_column='MATRICULA_PROVINCIAL', max_length=20, null=True, verbose_name='Matrícula Provincial')),
                ('dni', models.CharField(db_column='DNI', max_length=12, unique=True, verbose_name='DNI')),
                ('cuil', models.CharField(db_column='CUIL', max_length=15, unique=True, verbose_name='CUIL')),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=60, verbose_name='Apellido')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=60, verbose_name='Nombre')),
                ('telefono_celular', models.CharField(db_column='TELEFONO_CELULAR', max_length=25, verbose_name='Teléfono Celular')),
                ('email', models.EmailField(db_column='EMAIL', max_length=100, verbose_name='Correo Electrónico')),
                ('especialidad', models.ForeignKey(db_column='ESPECIALIDAD_ID', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='core.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'MEDICOS',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_column='DNI', max_length=12, unique=True, verbose_name='DNI')),
                ('cuil', models.CharField(db_column='CUIL', max_length=15, unique=True, verbose_name='CUIL')),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=60, verbose_name='Apellido')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=60, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO', verbose_name='Fecha de Nacimiento')),
                ('telefono_celular', models.CharField(db_column='TELEFONO_CELULAR', max_length=25, verbose_name='Teléfono Celular')),
                ('email', models.EmailField(db_column='EMAIL', max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=120, verbose_name='Dirección')),
                ('localidad', models.CharField(db_column='LOCALIDAD', default='CABA', max_length=60, verbose_name='Localidad')),
                ('provincia', models.CharField(db_column='PROVINCIA', default='Buenos Aires', max_length=60, verbose_name='Provincia')),
                ('obra_social', models.CharField(db_column='OBRA_SOCIAL', max_length=60, verbose_name='Obra Social / Cobertura')),
                ('numero_afiliado', models.CharField(db_column='NUMERO_AFILIADO', max_length=30, verbose_name='N° de Afiliado')),
                ('diagnostico_clinico', models.CharField(db_column='DIAGNOSTICO_CLINICO', max_length=255, verbose_name='Diagnóstico Principal')),
                ('historia_clinica', models.TextField(db_column='HISTORIA_CLINICA', verbose_name='Historia Clínica / Evolución')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, db_column='FECHA_INGRESO', verbose_name='Fecha de Ingreso')),
                ('medico_asignado', models.ForeignKey(blank=True, db_column='MEDICO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='core.medico', verbose_name='Médico de Cabecera')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'PACIENTES',
                'ordering': ['id'],
            },
        ),
    ]
